# Balance traffic across three instances of the MeshCore MQTT Broker Docker container
upstream meshcore-mqtt-broker-balanced {
    # Consider source IP address to persist sessions when possible
    ip_hash;
    # Prioritize broker_1 with a larger weight
    server broker_1:8883 weight=3;
    server broker_2:8883;
    server broker_3:8883;
}

# Use primary and only go to backup (for 60 seconds) in event of failover (after 1 failure)
upstream meshcore-mqtt-broker-backup {
    server primary_broker:8883 fail_timeout=60s max_fails=1;
    server backup_broker:8883 backup;
}
